# Generated by Django 3.1.3 on 2020-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201128_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(default='', max_length=8, null=True),
        ),
    ]
